### PR TITLE
Upgrade to 5.5

### PR DESCRIPTION
**Pull request by Booklordofthedings**
I ran the new parser with the updated generator output for 5.5 and am currently building the libs for windows and wasm.
Linux will be build when I get home.

Other than that this still needs to be tested

### CODE REVIEW

**Comment by Booklordofthedings** [comment]
@Starpelly  btw do we even need https://github.com/Starpelly/raylib-beef/blob/main/raylib-beef/libs/libs_x64/raylib.lib anymore ?
since raylibddl.lib + raylib.dll is for dynamic compilation and staticraylib.lib is for static compilation.

**Comment by Booklordofthedings** [comment]
wasm seems to currently be broken
the precompiled version throws this:
`wasm-ld: error: c:/Dev/raylib-beef/raylib-beef/libs/wasm/libraylib.a(rcore.o): undefined symbol: glfwSetWindowContentScaleCallback`

and attempting to compile it myself also errors

**Comment by Booklordofthedings** [comment]
Done 👍

**Comment by Starpelly** [comment]
@Booklordofthedings
I assume the generator just works with the new version? No changes to that needed?

**Comment by Booklordofthedings** [comment]
No changes that where obvious to me.
Your example ran on all platforms + one of my own projects also did.

I just make'd the raylib-api project and fed the resulting .json files into the generator and it worked without erroe.

**Comment by Starpelly** [comment]
My only concern is that the `raylib-api` submodule is out of date, do you think you could update that? Or is it fine?

**Comment by Booklordofthedings** [comment]
If I figure out how yes, but the source also doesnt have 5.5 yet.
Im going to try making a pr there.

**Comment by Starpelly** [comment]
Once that's complete, I'll merge.

**Comment by Booklordofthedings** [comment]
Submodule is now up to date for 5.5

**Pull request merged**
